package sbnz.integracija;

import sbnz.integracija.example.facts.*;
import sbnz.integracija.example.enums.*;
import java.time.*;
import java.util.List;


query "products with grade x-ic and less" (int x) 
    product : Preparation( review.rating < x )
end


query "products with grade x-ic and more" (int x) 
    product : Preparation( review.rating > x )
end


query "products with more than x-ic comments" (int x)
    product : Preparation( review.comments.size > x)
end

query "products with less than x-ic comments" (int x)
    product : Preparation( review.comments.size < x)
end
